### ISSUE TITLE
grextras cmake error missing gruel due to change in gnuradio 3.7

### ISSUE THREAD

**Issue by Dantali0n** [guruofquality/grextras#39]
Hello gruel is no longer available since gnuradio 3.7 this causes cmake to fail on:
`coudl not find module GRUEL`

see also: [online reference to problem](https://www.ruby-forum.com/topic/4416701)

**Comment by guruofquality** [comment]
GrExtras was last compatible with gr3.6. I think there are other compatibility issues besides GRUEL...

In any case, I stopped maintaining grextras because GRAS was finally maturing to usability and other features may have been included gnuradio. Is there anything in particular you are looking for with GrExtras?

I hope whatever you are looking for you can find in current gnuradio, or you should take a look at my currently maintained data flow framework, Pothos: https://github.com/pothosware/pothos/wiki

**Comment by Dantali0n** [comment]
Thanks for the heads-up, no particular reason grextras sounded pretty neat and I wanted to check it out. ill be sure to use Pothos instead.
